### ISSUE TITLE
功能请求：视频播放页，评论版块置于视频播放器右边

### ISSUE THREAD

**Issue by phtwo** [bilibili-helper/bilibili-helper-o#820]
## 场景
1. 边看视频边看评论
2. 长视频，方便点击评论里面的时间点

## 效果

![普通模式](https://user-images.githubusercontent.com/11756505/106460073-bdc7e700-64cd-11eb-959c-bccdbda70761.png)
![宽屏模式](https://user-images.githubusercontent.com/11756505/106460081-c02a4100-64cd-11eb-9042-80f890d04015.png)

**Comment by phtwo** [comment]
我写了一点 css 简单实现了效果，但希望插件有这个功能，切换比较方便，也可以设置默认模式

```css
/* ==UserStyle==
@name           bilibili 视频播放页 评论右置
@namespace      github.com/openstyles/stylus
@version        1.0.0
@description    评论右置
@author         ph2
==/UserStyle== */
@-moz-document url-prefix("https://www.bilibili.com/video/") {
    .v-wrap {
        width: initial;
        max-width: initial;
        justify-content: start;
        padding: 0 20px;
    }

    .l-con {
        position: relative;
    }

    .v-wrap .r-con {
        margin-top: calc( 96px + 721px + 100px);
    }

    .v-wrap #comment {
        position: absolute;
        top: 0;
        left: calc(100% + 10px);
        width: calc(100vw - 100% - 20 * 2px - 10px);
        height: calc( 96px + 721px - 20px);
        min-width: 320px;
        overflow: hidden;
        overflow-y: auto;
        box-shadow: 0 0 8px #e5e9ef;
    }

    #comment .common {
        padding: 0 5px;
    }

    .player-mode-widescreen .v-wrap #comment {
        left: calc(100% + 10px + (1394px - 1044px));
        width: calc(100vw - 100% - 20 * 2px - 10px - (1394px - 1044px));
        height: calc( 96px + 830px - 20px);
    }

    .player-mode-widescreen .v-wrap .r-con {
        margin-top: 0;
    }

    .player-mode-widescreen .bb-comment .comment-list .list-item .user-face {
        display: none;
    }
    .player-mode-widescreen .bb-comment .comment-list .list-item .con {
        margin-left: 5px;
    }
}
```
